/* soapServer.c
   Generated by gSOAP 2.8.17r from StlmDate.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.17r 2014-07-16 19:56:27 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "OnlWS:GetStlmDate"))
		return soap_serve_OnlWS__GetStlmDate(soap);
	if (!soap_match_tag(soap, soap->tag, "OnlWS:GetTZeroNodeInfo"))
		return soap_serve_OnlWS__GetTZeroNodeInfo(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_OnlWS__GetStlmDate(struct soap *soap)
{	struct OnlWS__GetStlmDate soap_tmp_OnlWS__GetStlmDate;
	struct OnlWS__StlmdateResp resp;
	soap_default_OnlWS__StlmdateResp(soap, &resp);
	soap_default_OnlWS__GetStlmDate(soap, &soap_tmp_OnlWS__GetStlmDate);
	if (!soap_get_OnlWS__GetStlmDate(soap, &soap_tmp_OnlWS__GetStlmDate, "OnlWS:GetStlmDate", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = OnlWS__GetStlmDate(soap, soap_tmp_OnlWS__GetStlmDate.option, &resp);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_OnlWS__StlmdateResp(soap, &resp);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_OnlWS__StlmdateResp(soap, &resp, "OnlWS:StlmdateResp", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_OnlWS__StlmdateResp(soap, &resp, "OnlWS:StlmdateResp", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_OnlWS__GetTZeroNodeInfo(struct soap *soap)
{	struct OnlWS__GetTZeroNodeInfo soap_tmp_OnlWS__GetTZeroNodeInfo;
	struct OnlWS__GetTZeroNodeInfoResponse soap_tmp_OnlWS__GetTZeroNodeInfoResponse;
	struct OnlWS__TZeroNodeInfoResp soap_tmp_OnlWS__TZeroNodeInfoResp;
	soap_default_OnlWS__GetTZeroNodeInfoResponse(soap, &soap_tmp_OnlWS__GetTZeroNodeInfoResponse);
	soap_default_OnlWS__TZeroNodeInfoResp(soap, &soap_tmp_OnlWS__TZeroNodeInfoResp);
	soap_tmp_OnlWS__GetTZeroNodeInfoResponse.resp = &soap_tmp_OnlWS__TZeroNodeInfoResp;
	soap_default_OnlWS__GetTZeroNodeInfo(soap, &soap_tmp_OnlWS__GetTZeroNodeInfo);
	if (!soap_get_OnlWS__GetTZeroNodeInfo(soap, &soap_tmp_OnlWS__GetTZeroNodeInfo, "OnlWS:GetTZeroNodeInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = OnlWS__GetTZeroNodeInfo(soap, soap_tmp_OnlWS__GetTZeroNodeInfo.option, soap_tmp_OnlWS__GetTZeroNodeInfoResponse.resp);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_OnlWS__GetTZeroNodeInfoResponse(soap, &soap_tmp_OnlWS__GetTZeroNodeInfoResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_OnlWS__GetTZeroNodeInfoResponse(soap, &soap_tmp_OnlWS__GetTZeroNodeInfoResponse, "OnlWS:GetTZeroNodeInfoResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_OnlWS__GetTZeroNodeInfoResponse(soap, &soap_tmp_OnlWS__GetTZeroNodeInfoResponse, "OnlWS:GetTZeroNodeInfoResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
